platform :ios, '8.0'

target 'Enesco' do
    pod 'DOUAudioStreamer'
    pod 'SDWebImage'
    pod 'GVUserDefaults'
    pod 'MBProgressHUD'
    pod 'Mantle', '1.5.5'
    pod 'AFNetworking'
    pod 'FMDB' ,'~> 2.7.2'
    pod 'SVProgressHUD'
    pod 'YTKNetwork'
    pod 'WSProgressHUD', '1.1.1'
    pod 'MJRefresh', '3.1.12'
    pod 'Reachability', '3.2'
    pod 'Masonry', '1.0.2'
    pod 'AJNotificationView', '0.7'
    pod 'TOWebViewController', '2.2.6'
    pod 'UIAlertView+Blocks', '0.9'
    pod 'IQKeyboardManager', '4.0.10'
    pod 'UMengAnalytics', '4.2.4'
    pod 'JPush'
    pod 'RTLabel', '1.0.1'



end
